steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/totemic-union-396517/github.com/caalzate91/cotizaTrabajoFree-pdn:${SHORT_SHA}', '.']
  # push the container image to Artifact (Antes Container Registry)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/totemic-union-396517/github.com/caalzate91/cotizaTrabajoFree-pdn:${SHORT_SHA}']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'cotizaTrabajoFree-pdn', '--image', 'gcr.io/totemic-union-396517/github.com/caalzate91/cotizaTrabajoFree-pdn:${SHORT_SHA}','--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  senv:
    - 'PORT=8080'
images:
  - gcr.io/totemic-union-396517/github.com/caalzate91/cotizaTrabajoFree-pdn